import { DiffError } from '../errors.ts';
import { resolveRepoLocation } from '../git/location.ts';
import { LocalRepository, type DiffRequest } from '../git/repository.ts';
import type { DiffSource, ResolvedDiff } from './types.ts';

export interface GitSourceContext {
	/** Directory that relative `repo` paths are resolved against. */
	base: string;
}

/** A diff generated by invoking Git against a repository. */
export class GitDiffSource implements DiffSource {
	readonly id: string;

	constructor(
		private readonly repo: string,
		private readonly request: DiffRequest,
		private readonly context: GitSourceContext,
	) {
		this.id = `git:${repo}:${request.commit ?? `${request.from ?? 'HEAD'}..${request.to ?? 'HEAD'}`}`;
	}

	async resolve(signal: AbortSignal): Promise<ResolvedDiff> {
		const location = await resolveRepoLocation(this.repo, this.context.base);

		if (location.kind === 'remote') {
			throw new DiffError(
				'Remote repositories are not supported yet',
				`\`${location.url}\` is a remote repository. Cloning and caching remote repositories is not implemented in this version; clone it locally and point \`repo\` at the clone.`,
			);
		}

		const repository = new LocalRepository(location.path);
		const options = { signal };

		await repository.assertValid(options);
		const { patch, from, to } = await repository.diff(this.request, options);

		return {
			patch,
			fromSha: from,
			toSha: to,
			origin: `${location.path} (${from.slice(0, 7)}..${to.slice(0, 7)})`,
		};
	}
}
